import {
  Loader2,
  Mail,
  Github,
  User,
  Settings,
  LogOut,
  LayoutDashboard,
  DollarSign,
  Users,
  CreditCard,
  Activity,
  Check,
  Clock,
  Info,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  gitHub: Github,
  user: User,
  settings: Settings,
  logout: LogOut,
  logo: LayoutDashboard,
  dollar: DollarSign,
  users: Users,
  creditCard: CreditCard,
  activity: Activity,
  check: Check,
  clock: Clock,
  info: Info,
} 